Bmo deep dive presentation
metal3-io/metal3-docs pull request #210
Opened 2022-01-12 16:44 UTC by hroyrh

A presentation to cover the BMO in detail.

2022-01-13 08:58 UTC, kashifest commented
/hold
Until default branch of the repo is main

2022-03-01 14:25 UTC, jklippel commented
This gives a lot of insight. I see the PR is on hold due to the default-branch name change. It was changed in the meantime.
Is there any other reason this is still on hold?

It is a really helpful piece of documentation that is currently hidden here.

2022-03-01 18:18 UTC, kashifest commented
/hold cancel

2022-06-17 09:32 UTC, furkatgofurov7 requested changes

2022-06-17 09:32 UTC, furkatgofurov7 commented on docs/presentations/bmo-deep-dive/bmo-deep-dive.html
> +									 data-background-image="https://github.com/metal3-io/metal3-docs/raw/master/images/metal3.png"
after branch switch (master ==> main), we need to update this and all other BMO reference links in the document accordingly

2022-06-17 09:32 UTC, furkatgofurov7 commented on docs/presentations/bmo-deep-dive/bmo-deep-dive.html
> +### Sample BareMetalHost Definition
```suggestion
### Sample BareMetalHost Custom Resource Definition
```

2022-06-17 09:32 UTC, furkatgofurov7 commented on docs/presentations/bmo-deep-dive/bmo-deep-dive.html
> +  name: bmo-master-0-bmc-secret
This does not match with the secret name provided in BMH later, it should be 
```suggestion
  name: bm0-bmc-secret
```

2022-06-17 09:32 UTC, furkatgofurov7 commented on docs/presentations/bmo-deep-dive/bmo-deep-dive.html
> +# Roadmap
Do we have one which is up-to-date?

2022-09-16 04:28 UTC, hroyrh commented
/remove-lifecycle stale

2022-12-15 05:56 UTC, hroyrh commented
/remove-lifecycle stale

2023-03-21 10:19 UTC, hroyrh commented
/remove-lifecycle stale

2023-07-19 10:41 UTC, closed without merging