Add unified OWNERS for user-guide patches reviews
metal3-io/metal3-docs pull request #256
Opened 2022-03-17 12:39 UTC by fmuyassarov

Add unified OWNERS for user-guide patches reviews so that
user guide patch reviewers are not blocked to give lgtm & approve
labels. This also means reviewers and approvers should give lgtm
and approve only in their area of expertise (GitHub project of Metal3.io)
or in other words where they actually have reviewer or approval rights.
/cc @zaneb @dtantsur @furkatgofurov7 @andfasano @kashifest

2022-03-17 12:39 UTC, fmuyassarov commented
/cc @Rozzii

2022-03-17 12:50 UTC, Rozzii reviewed
LGTM

2022-03-18 08:18 UTC, furkatgofurov7 requested changes
Looks good apart minor nit, please check:

2022-03-18 08:18 UTC, furkatgofurov7 commented on docs/user-guide/src/OWNERS
>  # See https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/OWNERS
This needs to be removed

2022-03-18 12:10 UTC, fmuyassarov commented on docs/user-guide/src/OWNERS
>  # See https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/OWNERS
thanks, fixed

2022-03-18 12:14 UTC, kashifest commented
/approve

2022-03-18 13:57 UTC, zaneb commented
/approve

2022-03-18 14:06 UTC, furkatgofurov7 reviewed
/lgtm

2022-03-18 14:07 UTC, merged