[WIP] Add how to build ironic images section
metal3-io/metal3-docs pull request #270
Opened 2022-07-07 13:51 UTC by elfosardo

Closes https://github.com/metal3-io/metal3-docs/issues/231

2022-10-10 07:55 UTC, elfosardo commented
/remove-lifecycle stale

2022-10-19 10:31 UTC, elfosardo commented
/cc @dtantsur @fmuyassarov

2022-10-19 13:56 UTC, Rozzii requested changes

2022-10-19 13:56 UTC, Rozzii commented on docs/user-guide/src/ironic/ironic-container-images.md
> +## Build ironic-image from source
Add a short description about the patching too please.

2022-10-26 08:14 UTC, Rozzii approved these changes

2022-10-26 08:15 UTC, Rozzii commented
Thank you for your contribution @elfosardo !
/lgtm

2022-10-31 08:57 UTC, furkatgofurov7 reviewed
Great work, found one small nit:

2022-10-31 08:57 UTC, furkatgofurov7 commented on docs/user-guide/src/ironic/ironic-container-images.md
> +| [ironic-image](https://github.com/metal3-io/ironic-image) | Ironic api and conductor / Ironic Inspector / Sushy tools |
Is not is also:
```suggestion
| [ironic-image](https://github.com/metal3-io/ironic-image) | Ironic api and conductor / Ironic Inspector / Sushy tools and virtualbmc |
```
?

2022-11-02 10:53 UTC, elfosardo commented on docs/user-guide/src/ironic/ironic-container-images.md
> +| [ironic-image](https://github.com/metal3-io/ironic-image) | Ironic api and conductor / Ironic Inspector / Sushy tools |
you are totally right, I will update it

2022-11-02 10:54 UTC, elfosardo commented
/cc @dtantsur @iurygregory

2022-11-03 10:15 UTC, furkatgofurov7 commented
Can Ironic repo maintainers take a look at this and help to merge it? 
/cc @dtantsur @bfournie @iurygregory

2022-11-03 13:23 UTC, smoshiur1237 approved these changes
LGTM

2022-11-04 08:20 UTC, Rozzii commented
/lgtm

2022-11-04 08:21 UTC, Rozzii approved these changes

2022-11-04 13:15 UTC, furkatgofurov7 commented
@elfosardo can you please fix the rebase issues, we had some PRs landing recently, thanks!

2022-11-04 13:22 UTC, furkatgofurov7 approved these changes
/approve

/cc @Rozzii

2022-11-04 13:36 UTC, smoshiur1237 reviewed
/lgtm

2022-11-04 13:38 UTC, merged