Updated TODO for Ironic installation
metal3-io/metal3-docs pull request #324
Opened 2023-04-20 15:50 UTC by SafeEHA

Under 4.1 Install cluster-api metal3 provider [TODO](https://book.metal3.io/capm3/TODO) returns an error when clicked so i found the correct [link](https://book.metal3.io/ironic/ironic_installation.html) and updated it

2023-04-20 16:52 UTC, furkatgofurov7 requested changes
/ok-to-test

Can you also please squash your commits?

2023-04-20 16:52 UTC, furkatgofurov7 commented on docs/user-guide/src/capm3/installation_guide.md
> +1. Install Ironic, refer to [TODO](https://book.metal3.io/ironic/ironic_installation.html).
```suggestion
1. Install Ironic, refer to [this page](https://book.metal3.io/ironic/ironic_installation.html).
```

2023-04-20 17:15 UTC, SafeEHA commented
Yes, I would do so now
Thanks for your suggestion

Please I also noticed that 2.1 Install baremetal operator is not accessible
Do you by chance know whats the issue?

2023-04-21 11:40 UTC, dtantsur commented
Seems not squashed still. You can use `git rebase -i` or just re-create the commit.

2023-04-21 16:05 UTC, SafeEHA commented
I might have to re-create the commit, for some reason I can't see my commit when I `git rebase -i` but I can see others

2023-04-24 12:07 UTC, tuminoid commented
> I might have to re-create the commit, for some reason I can't see my commit when I `git rebase -i` but I can see others

`git rebase -i HEAD~5` should include all your 4 commits, and you can squash them.

2023-04-26 06:09 UTC, closed without merging