fixed link
metal3-io/metal3-docs pull request #477
Opened 2024-10-03 20:23 UTC by JasonHo420

fixed the dead link

Issue #443

2024-10-04 04:40 UTC, tuminoid commented
/ok-to-test

2024-10-04 04:41 UTC, tuminoid commented
Thanks for the contribution! Please sign-off your commit to fix DCO test, and also give the PR a bit more descriptive title.

2024-10-22 05:55 UTC, Rozzii requested changes
Fix your DCO issue please.
Commint can be signed e.g `git commit -s`
@JasonHo420

2025-01-20 06:54 UTC, tuminoid commented
Stale. Superseded by https://github.com/metal3-io/metal3-docs/pull/498 .

/close

2025-01-20 06:54 UTC, closed without merging